on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: sudo apt -y install graphviz wget 
      - run: wget https://github.com/plantuml/plantuml/releases/download/v1.2025.3/plantuml-mit-1.2025.3.jar
      - run: mkdir -p ~/.local/bin/ && mv plantuml-mit-1.2025.3.jar ~/.local/bin/
      - run: chmod + ~/.local/bin/plantuml
      - run: pip install mkdocs-material plantum-markdown
      - run: mkdocs gh-deploy --force -d ./docs
