on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          github_token: ${{ secrets.GITHUB_TOKEN }} 
      - run: sudo apt -y install graphviz wget 
      - run: wget https://github.com/plantuml/plantuml/releases/download/v1.2025.3/plantuml-mit-1.2025.3.jar
      - run: mkdir -p ~/.local/bin/ && mv plantuml-mit-1.2025.3.jar ~/.local/bin/
      - run: echo "#!/bin/bash" > ~/.local/bin/plantuml
      - run: echo "export LANG=ja_JP.UTF-8" >>   ~/.local/bin/plantuml
      - run: echo "/usr/bin/java -Djava.io.tmpdir=/var/tmp -Djava.awt.headless=true -jar ~/.local/bin/plantuml-mit-1.2025.3.jar -charset UTF-8 $*"  >> ~/.local/bin/plantuml
      - run: chmod +x ~/.local/bin/plantuml
      - run: pip install mkdocs mkdocs-material plantuml-markdown
      - run: mkdocs gh-deploy
